DROP DATABASE IF EXISTS movie_db;
CREATE movie_db;

DROP TABLE IF EXISTS movies;
CREATE TABLE movies (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  movie_name VARCHAR(100) NOT NULL,
);

DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (
--   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  movie_name VARCHAR(100) NOT NULL,
  review TEXT NOT NULL,
  review_id INT,
  FOREIGN KEY (id)
  REFERENCES movies(id)
  ON DELETE SET NULL
);